// Datos de demostración para cuando la base de datos no esté disponible (Vercel con SQLite)

export const demoCategories = [
    { id: 1, name: 'Vestidos', createdAt: new Date() },
    { id: 2, name: 'Blusas', createdAt: new Date() },
    { id: 3, name: 'Accesorios', createdAt: new Date() },
    { id: 4, name: 'Calzado', createdAt: new Date() },
];

export const demoProducts = [
    {
        id: 1,
        name: 'Vestido Floral Verano',
        description: 'Vestido ligero con estampado floral, perfecto para días soleados. Tela suave y cómoda.',
        priceUsd: 45.00,
        oldPriceUsd: 65.00,
        isOffer: true,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
        categoryId: 1,
        category: demoCategories[0],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: 'Blusa Elegante Blanca',
        description: 'Blusa de seda con detalles delicados. Ideal para ocasiones especiales.',
        priceUsd: 35.00,
        oldPriceUsd: null,
        isOffer: false,
        stock: 15,
        image: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600',
        categoryId: 2,
        category: demoCategories[1],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: 'Aretes Dorados Minimalistas',
        description: 'Juego de aretes en tono dorado con diseño minimalista y elegante.',
        priceUsd: 18.00,
        oldPriceUsd: null,
        isOffer: false,
        stock: 25,
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600',
        categoryId: 3,
        category: demoCategories[2],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: 'Sandalias Casuales',
        description: 'Sandalias cómodas para el día a día. Diseño moderno y versátil.',
        priceUsd: 28.00,
        oldPriceUsd: 38.00,
        isOffer: true,
        stock: 3,
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
        categoryId: 4,
        category: demoCategories[3],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        name: 'Vestido Negro Elegante',
        description: 'El clásico vestido negro que no puede faltar. Corte favorecedor y tela premium.',
        priceUsd: 55.00,
        oldPriceUsd: null,
        isOffer: false,
        stock: 12,
        image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600',
        categoryId: 1,
        category: demoCategories[0],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        name: 'Collar Perlas Naturales',
        description: 'Collar con perlas cultivadas de agua dulce. Elegancia atemporal.',
        priceUsd: 42.00,
        oldPriceUsd: 55.00,
        isOffer: true,
        stock: 7,
        image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600',
        categoryId: 3,
        category: demoCategories[2],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export const demoSlides = [
    {
        id: 1,
        title: 'Elegancia Sin Esfuerzo',
        subtitle: 'Descubre nuestra nueva colección de piezas minimalistas diseñadas para la mujer moderna.',
        buttonText: 'Ver Colección',
        buttonLink: '#products',
        image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1200',
        badge: 'Nueva Colección',
        isActive: true,
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        title: 'Temporada de Ofertas',
        subtitle: 'Aprovecha descuentos increíbles en artículos seleccionados. ¡Ofertas por tiempo limitado!',
        buttonText: 'Ver Ofertas',
        buttonLink: '#products',
        image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1200',
        badge: '¡Ofertas!',
        isActive: true,
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
